# Copyright BigchainDB GmbH and BigchainDB contributors
# SPDX-License-Identifier: (Apache-2.0 AND CC-BY-4.0)
# Code is Apache-2.0 and docs are CC-BY-4.0

language: python
python:
  - 3.5
  - 3.6

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.19.0
  matrix:
    - TOXENV=py35
    - TOXENV=py36
    - TOXENV=flake8
    - TOXENV=docs

matrix:
  fast_finish: true
  exclude:
    - python: 3.5
      env: TOXENV=flake8
    - python: 3.5
      env: TOXENV=docs
    - python: 3.5
      env: TOXENV=py36
    - python: 3.6
      env: TOXENV=py35

before_install:
  - sudo .ci/travis-before-install.sh

install:
  - .ci/travis-install.sh

before_script:
  - .ci/travis-before-script.sh

script: .ci/travis_script.sh

after_success:
  - .ci/travis-after-success.sh
