language: python
python:
  - 3.5
  - 3.6

env:
  - TOXENV=flake8
  - TOXENV=docs
  #- TOXENV=py35-rethinkdb
  #- TOXENV=py35-mongodb
  #- TOXENV=py36-rethinkdb
  #- TOXENV=py36-mongodb

matrix:
  fast_finish: true
  exclude:
  - python: 3.5
    env: TOXENV=flake8
  - python: 3.5
    env: TOXENV=docs
  include:
  - python: 3.5
    addons:
      rethinkdb: '2.3.5'
    env:
      - BIGCHAINDB_DATABASE_BACKEND=rethinkdb
      - TOXENV=py35-rethinkdb
  - python: 3.5
    env:
      - BIGCHAINDB_DATABASE_BACKEND=mongodb
      - TOXENV=py35-mongodb
  - python: 3.6
    addons:
      rethinkdb: '2.3.5'
    env:
      - BIGCHAINDB_DATABASE_BACKEND=rethinkdb
      - TOXENV=py36-rethinkdb
  - python: 3.6
    env:
      - BIGCHAINDB_DATABASE_BACKEND=mongodb
      - TOXENV=py36-mongodb

install: .ci/travis-install.sh

before_script: .ci/travis-before-script.sh

script: .ci/travis-script.sh

after_success: .ci/travis-after-success.sh
