language: python
python: 3.5

env:
  - TOXENV=py35
  - TOXENV=flake8

before_install:
  - source /etc/lsb-release
  - echo "deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main" | sudo tee -a /etc/apt/sources.list.d/rethinkdb.list
  - wget -qO- https://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
  - sudo apt-get update -qq

install:
  - sudo apt-get install rethinkdb
  - pip install "git+https://github.com/sbellem/bigchaindb.git@setup-no-pinning"
  - pip install -U codecov tox

before_script:
  - rethinkdb --daemon
  - bigchaindb -y configure
  #- bigchaindb start
  - nohup bigchaindb start >/dev/null 2>/dev/null &

script: tox -e ${TOXENV}

after_success: codecov
