codecov:
  branch: master

coverage:
  range: "95...100"

ignore:
  - "docs/*"
  - "tests/*"
  - "bigchaindb_driver/common/*"

comment:
  layout: "header, diff, changes, sunburst, uncovered"
  behavior: default
